// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwh01bl3cp5lBvvz5Uo43xOi2KZOoynu8',
    appId: '1:646719381567:web:5224dd12735846bbbf588a',
    messagingSenderId: '646719381567',
    projectId: 'smartcheck999',
    authDomain: 'smartcheck999.firebaseapp.com',
    storageBucket: 'smartcheck999.firebasestorage.app',
    measurementId: 'G-9YLSQGSG0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIyYomJuwWzdT9IqpeyJ4sjYHv5-KR-w',
    appId: '1:646719381567:android:f461d4e02b82c138bf588a',
    messagingSenderId: '646719381567',
    projectId: 'smartcheck999',
    storageBucket: 'smartcheck999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZqbP_hmQClveXip0ur5iUAvdstLlDVV4',
    appId: '1:646719381567:ios:7049f66dc76db119bf588a',
    messagingSenderId: '646719381567',
    projectId: 'smartcheck999',
    storageBucket: 'smartcheck999.firebasestorage.app',
    iosBundleId: 'com.example.smartcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZqbP_hmQClveXip0ur5iUAvdstLlDVV4',
    appId: '1:646719381567:ios:7049f66dc76db119bf588a',
    messagingSenderId: '646719381567',
    projectId: 'smartcheck999',
    storageBucket: 'smartcheck999.firebasestorage.app',
    iosBundleId: 'com.example.smartcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwh01bl3cp5lBvvz5Uo43xOi2KZOoynu8',
    appId: '1:646719381567:web:4e0afb1d992ddbe1bf588a',
    messagingSenderId: '646719381567',
    projectId: 'smartcheck999',
    authDomain: 'smartcheck999.firebaseapp.com',
    storageBucket: 'smartcheck999.firebasestorage.app',
    measurementId: 'G-J1HER1HY55',
  );
}
